export const INITIAL_ORDER = "INITIAL_ORDER";

export const SPINNING = "SPINNING";

export const RESET_ORDER = "RESET_ORDER";

export const EXCHANGE_RATE = "EXCHANGE_RATE";

export const EXCHANGE_RATE_SPINNING = "EXCHANGE_RATE_SPINNING";
