export const INITIAL_ORDER = "INITIAL_ORDER";

export const SPINNING = "SPINNING";

export const RESET_ORDER = "RESET_ORDER";

export const EXCHANGE_RATE = "EXCHANGE_RATE";

export const EXCHANGE_RATE_SPINNING = "EXCHANGE_RATE_SPINNING";

export const SUBMIT_LOADING = "SUBMIT_LOADING";

export const CONFIRMATION_SPINNING = "CONFIRMATION_SPINNING";

export const SHOW_CONFIRMATION = "SHOW_CONFIRMATION";

export const CONFIRMATION_DATA = "CONFIRMATION_DATA";

export const CONFIRM_LOADING = "CONFIRM_LOADING";

export const SHOW_CONFIRMATION_RESULT_DIALOG =
  "SHOW_CONFIRMATION_RESULT_DIALOG";

export const RESET_ORDER_STORE = "RESET_ORDER_STORE";

export const CONFIRM_RESULT = "CONFIRM_RESULT" ;

export const INITIAL_SETTINGS = "INITIAL_SETTINGS";
