export const RESET_SUCCESS = "RESET_SUCCESS";

export const SUBMIT_BUTTON_LOADING = "SUBMIT_BUTTON_LOADING";

export const SEND_CODE_SUCCESS = "SEND_CODE_SUCCESS";

export const SEND_CODE_BUTTON_LOADING = "SEND_CODE_BUTTON_LOADING";